name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/osx_64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run 20114934-c5a51187-a3f5-4206-a16d-fafa4ab44fe6 -e 20114934-5776b81e-3525-4571-a827-416160e5ff74 -i 20114934-7744d2a1-07d3-41e8-8757-c10aea996948 //signup signin -i 20114934-eaca1fe9-da33-4fb5-b447-953734832811 //contacts
          
